-- Adds the per-item pre-call lease used by recoverInterruptedApplePayJobs
-- to distinguish a crashed worker (lease expired) from a still-live one
-- during multi-instance rolling restarts. See task #265.
--
-- Note: drizzle-kit also detected `orphan_cleanup_audits` as missing from
-- the previous snapshot, but that table is created by the hand-named
-- migration `0016_add_orphan_cleanup_audits.sql` shipped with task #262,
-- so it is intentionally NOT re-created here. The 0003 snapshot
-- correctly reflects the table's existence so future drizzle-kit
-- migrations diff against the right baseline.
ALTER TABLE "apple_pay_job_items" ADD COLUMN "claimed_at" timestamp;
