import { getTestDb } from "../setup/test-db";
import { bowlerLeagues, bowlers, bowlerPaymentLinks, leagueOccurrenceBillingTerms, leagueOccurrenceBillingTermRevisions, leagueOccurrenceGenerationRuns, leagueOccurrenceRevisions, leagueOccurrences, leagueScheduleCommands, leagues, locations, organizations, teams, users } from "@shared/schema";
import { getCanonicalActivationSource, activateCanonicalFinancials } from "../../server/services/canonical-due-past-due";

/** A complete, isolated F1/F3 weekly fixture for mounted-router tests. */
export async function makeF3WorkflowFixture() {
  const db = getTestDb();
  const suffix = `${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const [organization] = await db.insert(organizations).values({ name: `F3 route ${suffix}`, slug: `f3-route-${suffix}` }).returning({ id: organizations.id });
  const [actor] = await db.insert(users).values({ email: `f3-route-${suffix}@example.test`, password: "test", name: "F3 route admin", role: "org_admin", organizationId: organization.id }).returning({ id: users.id });
  const [location] = await db.insert(locations).values({ name: "F3 route lanes", organizationId: organization.id }).returning({ id: locations.id });
  const [league] = await db.insert(leagues).values({ name: `F3 route league ${suffix}`, organizationId: organization.id, locationId: location.id, seasonStart: "2038-01-01", seasonEnd: "2038-12-31", weekDay: "Sunday", competitionStartTime: "19:00", timezone: "UTC", totalBowlingWeeks: 2, weeklyFee: 500, paymentMode: "weekly" }).returning({ id: leagues.id });
  const [team] = await db.insert(teams).values({ name: `F3 route team ${suffix}`, number: 1, leagueId: league.id }).returning({ id: teams.id });
  const roster = await db.insert(bowlers).values([0, 1, 2].map((index) => ({ name: `F3 route bowler ${index} ${suffix}`, organizationId: organization.id, active: true, paymentCustomerId: `route-customer-${index}-${suffix}`, paymentProviderLocationId: location.id }))).returning({ id: bowlers.id });
  await db.insert(bowlerLeagues).values(roster.map((bowler) => ({ bowlerId: bowler.id, leagueId: league.id, teamId: team.id, active: true })));
  await db.insert(bowlerPaymentLinks).values({ bowlerAId: Math.min(roster[0].id, roster[1].id), bowlerBId: Math.max(roster[0].id, roster[1].id), organizationId: organization.id, status: "accepted", createdByUserId: actor.id, respondedAt: "2037-12-01T00:00:00.000Z" });
  const [command] = await db.insert(leagueScheduleCommands).values({ organizationId: organization.id, leagueId: league.id, actorUserId: actor.id, commandType: "publish", reason: "F3 route fixture", idempotencyKey: `f3-route-publish-${suffix}`, requestFingerprint: `lvf3route:${suffix}` }).returning({ id: leagueScheduleCommands.id });
  const [run] = await db.insert(leagueOccurrenceGenerationRuns).values({ organizationId: organization.id, leagueId: league.id, originatingCommandId: command.id, generatorVersion: "f3-route-fixture/1", inputFingerprint: `lvf3route-run:${suffix}`, sourceScheduleRevision: 1, normalizedInputSnapshot: { fixture: "f3-route" }, rangeStartDate: "2038-01-01", rangeEndDate: "2038-12-31", candidateOccurrenceCount: 2, generatedOccurrenceCount: 2, state: "applied", approvedAt: "2037-12-01T00:00:00.000Z", approvedByUserId: actor.id, approvalCommandId: command.id }).returning({ id: leagueOccurrenceGenerationRuns.id });
  const occurrenceIds: string[] = [];
  for (const index of [0, 1]) {
    const date = `2038-02-0${index + 1}`;
    const [occurrence] = await db.insert(leagueOccurrences).values({ organizationId: organization.id, leagueId: league.id, locationId: location.id, generationKey: `f3-route-occurrence-${suffix}-${index}`, generationRunId: run.id, kind: "regular", status: "scheduled", lifecycle: "published", authoritativeLocalDate: date, authoritativeLocalStartTime: "19:00:00", timezone: "UTC", startAt: `${date}T19:00:00.000Z`, selectedUtcOffsetMinutes: 0, foldResolution: "unambiguous", resolverVersion: "f3-route-fixture/1", plannedOrdinal: index + 1, competitionNumber: index + 1, competitive: true, countsInStandings: true, currentRevision: 1, lastCommandId: command.id, publishedAt: "2037-12-01T00:00:00.000Z", publishedByUserId: actor.id, publicationCommandId: command.id }).returning({ id: leagueOccurrences.id });
    occurrenceIds.push(occurrence.id);
    const [term] = await db.insert(leagueOccurrenceBillingTerms).values({ organizationId: organization.id, leagueId: league.id, occurrenceId: occurrence.id, purpose: "league_weekly_fee", obligationPolicy: "eligible_bowlers", defaultAmountMinor: 500, currency: "USD", billingOrdinal: index + 1, version: 1, state: "published", currentRevision: 1, lastCommandId: command.id, publishedAt: "2037-12-01T00:00:00.000Z", publishedByUserId: actor.id, publicationCommandId: command.id }).returning({ id: leagueOccurrenceBillingTerms.id });
    await db.insert(leagueOccurrenceBillingTermRevisions).values({ organizationId: organization.id, leagueId: league.id, billingTermId: term.id, commandId: command.id, revisionNumber: 1, snapshotSchemaVersion: 1, afterSnapshot: { id: term.id, organizationId: organization.id, leagueId: league.id, occurrenceId: occurrence.id, purpose: "league_weekly_fee", obligationPolicy: "eligible_bowlers", defaultAmountMinor: 500, currency: "USD", billingOrdinal: index + 1, version: 1, state: "published", currentRevision: 1, lastCommandId: command.id } });
    await db.insert(leagueOccurrenceRevisions).values({ organizationId: organization.id, leagueId: league.id, occurrenceId: occurrence.id, commandId: command.id, revisionNumber: 1, snapshotSchemaVersion: 1, afterSnapshot: { lifecycle: "published", status: "scheduled" } });
  }
  const activationSource = await getCanonicalActivationSource({ organizationId: organization.id, leagueId: league.id });
  const responsibilities = occurrenceIds.flatMap((occurrenceId) => roster.map((bowler, slotIndex) => ({ occurrenceId, teamId: team.id, slotIndex, bowlerId: bowler.id, role: "regular" as const, provenance: "explicit_admin_selection" as const })));
  const activation = await activateCanonicalFinancials({ organizationId: organization.id, leagueId: league.id, actorUserId: actor.id, commandKey: `f3-route-activation-${suffix}`, sourceFingerprint: activationSource.sourceFingerprint, payingLineupSize: 3, responsibilities });
  return { organizationId: organization.id, leagueId: league.id, actorUserId: actor.id, locationId: location.id, roster, occurrenceIds, activationId: activation.activationId, activationSourceFingerprint: activationSource.sourceFingerprint };
}
